import type {
  HannaAttraction,
  HannaDiningLocation,
  HannaEntertainmentExperience,
  HannaKnowledgeProvenance,
  HannaPark,
  HannaParkArea,
  HannaPlanningSignal,
  HannaResort,
  HannaTransportationConnection,
} from "@/lib/pixie/knowledge/types";

const stable: HannaKnowledgeProvenance = {
  sourceType: "curated_hanna",
  freshnessClass: "stable",
  status: "verified",
};

const refreshable: HannaKnowledgeProvenance = {
  sourceType: "curated_hanna",
  freshnessClass: "refreshable",
  status: "verified",
  verifiedAt: "2026-08-12",
};

const diningReview: HannaKnowledgeProvenance = {
  sourceType: "curated_hanna",
  freshnessClass: "refreshable",
  status: "needs_review",
  verifiedAt: "2026-08-13",
};

const heightReview: HannaKnowledgeProvenance = {
  sourceType: "curated_hanna",
  freshnessClass: "refreshable",
  status: "needs_review",
  verifiedAt: "2026-08-12",
};

const editorial: HannaKnowledgeProvenance = {
  sourceType: "curated_hanna",
  freshnessClass: "hanna_editorial",
  status: "verified",
};

export const HANNA_V1_PARKS: HannaPark[] = [
  { id: "park_magic_kingdom", entityType: "park", name: "Magic Kingdom", shortName: "Magic Kingdom", aliases: ["mk"], tags: ["magic_kingdom"], provenance: stable },
  { id: "park_epcot", entityType: "park", name: "EPCOT", aliases: ["epcot"], tags: ["epcot"], provenance: stable },
  {
    id: "park_hollywood_studios",
    entityType: "park",
    name: "Disney's Hollywood Studios",
    shortName: "Hollywood Studios",
    aliases: ["hollywood studios", "dhs"],
    tags: ["hollywood_studios"],
    provenance: stable,
  },
  {
    id: "park_animal_kingdom",
    entityType: "park",
    name: "Disney's Animal Kingdom",
    shortName: "Animal Kingdom",
    aliases: ["animal kingdom", "dak"],
    tags: ["animal_kingdom"],
    provenance: stable,
  },
];

export const HANNA_V1_AREAS: HannaParkArea[] = [
  { id: "area_mk_main_street", entityType: "area", name: "Main Street, U.S.A.", aliases: ["main street", "main street usa"], parkId: "park_magic_kingdom", tags: ["magic_kingdom", "entrance"], provenance: stable },
  { id: "area_mk_adventureland", entityType: "area", name: "Adventureland", aliases: ["adventureland"], parkId: "park_magic_kingdom", tags: ["magic_kingdom"], provenance: stable },
  { id: "area_mk_frontierland", entityType: "area", name: "Frontierland", aliases: ["frontierland"], parkId: "park_magic_kingdom", tags: ["magic_kingdom"], provenance: stable },
  { id: "area_mk_liberty_square", entityType: "area", name: "Liberty Square", aliases: ["liberty square"], parkId: "park_magic_kingdom", tags: ["magic_kingdom"], provenance: stable },
  { id: "area_mk_fantasyland", entityType: "area", name: "Fantasyland", aliases: ["fantasyland"], parkId: "park_magic_kingdom", tags: ["magic_kingdom", "toddler", "family"], provenance: stable },
  { id: "area_mk_tomorrowland", entityType: "area", name: "Tomorrowland", aliases: ["tomorrowland"], parkId: "park_magic_kingdom", tags: ["magic_kingdom"], provenance: stable },
  { id: "area_epcot_world_celebration", entityType: "area", name: "World Celebration", aliases: ["world celebration"], parkId: "park_epcot", tags: ["epcot"], provenance: stable },
  { id: "area_epcot_world_discovery", entityType: "area", name: "World Discovery", aliases: ["world discovery"], parkId: "park_epcot", tags: ["epcot", "thrill"], provenance: stable },
  { id: "area_epcot_world_nature", entityType: "area", name: "World Nature", aliases: ["world nature"], parkId: "park_epcot", tags: ["epcot", "rest", "indoor"], provenance: stable },
  { id: "area_epcot_world_showcase", entityType: "area", name: "World Showcase", aliases: ["epcot world showcase"], parkId: "park_epcot", tags: ["epcot", "dining"], provenance: stable },
  { id: "area_epcot_italy", entityType: "area", name: "Italy Pavilion", aliases: ["italy"], parkId: "park_epcot", parentAreaId: "area_epcot_world_showcase", tags: ["epcot", "world_showcase"], provenance: stable },
  { id: "area_epcot_france", entityType: "area", name: "France Pavilion", aliases: ["france"], parkId: "park_epcot", parentAreaId: "area_epcot_world_showcase", tags: ["epcot", "world_showcase"], provenance: stable },
  { id: "area_epcot_uk", entityType: "area", name: "United Kingdom Pavilion", aliases: ["uk pavilion", "united kingdom"], parkId: "park_epcot", parentAreaId: "area_epcot_world_showcase", tags: ["epcot", "world_showcase"], provenance: stable },
  { id: "area_epcot_germany", entityType: "area", name: "Germany Pavilion", aliases: ["germany"], parkId: "park_epcot", parentAreaId: "area_epcot_world_showcase", tags: ["epcot", "world_showcase"], provenance: stable },
  { id: "area_epcot_canada", entityType: "area", name: "Canada Pavilion", aliases: ["canada"], parkId: "park_epcot", parentAreaId: "area_epcot_world_showcase", tags: ["epcot", "world_showcase"], provenance: stable },
  { id: "area_epcot_the_land", entityType: "area", name: "The Land", aliases: ["land pavilion"], parkId: "park_epcot", tags: ["epcot", "future_world", "world_nature"], provenance: stable },
  { id: "area_epcot_international_gateway", entityType: "area", name: "International Gateway", aliases: ["epcot international gateway"], parkId: "park_epcot", tags: ["epcot", "boardwalk", "walking"], provenance: stable },
  { id: "area_epcot_resort_area", entityType: "area", name: "EPCOT Resort Area", aliases: ["boardwalk area", "epcot resorts"], tags: ["epcot", "resort_area", "walking"], provenance: stable },
  { id: "area_mk_resort_area", entityType: "area", name: "Magic Kingdom Resort Area", aliases: ["monorail resorts"], tags: ["magic_kingdom", "resort_area"], provenance: stable },
  { id: "area_disney_springs", entityType: "area", name: "Disney Springs", aliases: ["disney springs"], tags: ["disney_springs", "shopping_dining"], provenance: stable },
  { id: "area_hs_hollywood_boulevard", entityType: "area", name: "Hollywood Boulevard", aliases: ["hollywood boulevard"], parkId: "park_hollywood_studios", tags: ["hollywood_studios", "entrance"], provenance: stable },
  { id: "area_hs_sunset_boulevard", entityType: "area", name: "Sunset Boulevard", aliases: ["sunset boulevard"], parkId: "park_hollywood_studios", tags: ["hollywood_studios", "shows", "thrill"], provenance: stable },
  { id: "area_hs_toy_story_land", entityType: "area", name: "Toy Story Land", aliases: ["toy story land"], parkId: "park_hollywood_studios", tags: ["hollywood_studios", "family"], provenance: stable },
  { id: "area_hs_galaxys_edge", entityType: "area", name: "Star Wars: Galaxy's Edge", aliases: ["galaxys edge", "galaxy's edge", "star wars land"], parkId: "park_hollywood_studios", tags: ["hollywood_studios", "star_wars"], provenance: stable },
  { id: "area_hs_animation_courtyard", entityType: "area", name: "Animation Courtyard", aliases: ["animation courtyard"], parkId: "park_hollywood_studios", tags: ["hollywood_studios", "family"], provenance: stable },
  { id: "area_ak_oasis", entityType: "area", name: "Oasis", aliases: ["oasis"], parkId: "park_animal_kingdom", tags: ["animal_kingdom", "entrance"], provenance: stable },
  { id: "area_ak_discovery_island", entityType: "area", name: "Discovery Island", aliases: ["discovery island"], parkId: "park_animal_kingdom", tags: ["animal_kingdom", "central"], provenance: stable },
  { id: "area_ak_pandora", entityType: "area", name: "Pandora - The World of Avatar", aliases: ["pandora", "avatar land"], parkId: "park_animal_kingdom", tags: ["animal_kingdom", "avatar"], provenance: stable },
  { id: "area_ak_africa", entityType: "area", name: "Africa", aliases: ["africa", "harambe"], parkId: "park_animal_kingdom", tags: ["animal_kingdom", "safari"], provenance: stable },
  { id: "area_ak_asia", entityType: "area", name: "Asia", aliases: ["asia"], parkId: "park_animal_kingdom", tags: ["animal_kingdom", "thrill"], provenance: stable },
  { id: "area_ak_dinoland", entityType: "area", name: "DinoLand U.S.A. transition area", aliases: ["dinoland", "dinoland usa"], parkId: "park_animal_kingdom", tags: ["animal_kingdom", "needs_review"], provenance: refreshable, status: "needs_review" },
];

export const HANNA_V1_RESORTS: HannaResort[] = [
  {
    id: "resort_boardwalk_villas",
    entityType: "resort",
    name: "Disney's BoardWalk Villas",
    aliases: ["boardwalk", "boardwalk villas", "bwv", "disney boardwalk"],
    resortType: "dvc",
    areaId: "area_epcot_resort_area",
    parkAccess: ["park_epcot", "park_hollywood_studios"],
    transportationModes: ["walk", "boat"],
    tags: ["epcot", "dvc", "walking", "international_gateway"],
    provenance: stable,
  },
  {
    id: "resort_animal_kingdom_villas",
    entityType: "resort",
    name: "Disney's Animal Kingdom Villas",
    aliases: ["animal kingdom villas", "akv", "kidani village", "jambo house"],
    resortType: "dvc",
    parkAccess: ["park_animal_kingdom"],
    transportationModes: ["bus"],
    tags: ["animal_kingdom", "dvc"],
    provenance: stable,
  },
  {
    id: "resort_bay_lake_tower",
    entityType: "resort",
    name: "Bay Lake Tower at Disney's Contemporary Resort",
    aliases: ["bay lake tower", "blt"],
    resortType: "dvc",
    areaId: "area_mk_resort_area",
    parkAccess: ["park_magic_kingdom"],
    transportationModes: ["walk", "monorail"],
    tags: ["magic_kingdom", "dvc", "walking", "monorail"],
    provenance: stable,
  },
  {
    id: "resort_polynesian_villas",
    entityType: "resort",
    name: "Disney's Polynesian Villas & Bungalows",
    aliases: ["polynesian villas", "poly", "pvb"],
    resortType: "dvc",
    areaId: "area_mk_resort_area",
    parkAccess: ["park_magic_kingdom"],
    transportationModes: ["monorail", "boat"],
    tags: ["magic_kingdom", "dvc", "monorail"],
    provenance: stable,
  },
  {
    id: "resort_grand_floridian_villas",
    entityType: "resort",
    name: "The Villas at Disney's Grand Floridian Resort & Spa",
    aliases: ["grand floridian villas", "vgf"],
    resortType: "dvc",
    areaId: "area_mk_resort_area",
    parkAccess: ["park_magic_kingdom"],
    transportationModes: ["walk", "monorail", "boat"],
    tags: ["magic_kingdom", "dvc", "walking", "monorail"],
    provenance: stable,
  },
  {
    id: "resort_saratoga_springs",
    entityType: "resort",
    name: "Disney's Saratoga Springs Resort & Spa",
    aliases: ["saratoga", "saratoga springs", "ssr"],
    resortType: "dvc",
    parkAccess: [],
    transportationModes: ["walk", "boat", "bus"],
    tags: ["disney_springs", "dvc"],
    provenance: stable,
  },
  {
    id: "resort_riviera",
    entityType: "resort",
    name: "Disney's Riviera Resort",
    aliases: ["riviera", "rva"],
    resortType: "dvc",
    parkAccess: ["park_epcot", "park_hollywood_studios"],
    transportationModes: ["skyliner", "bus"],
    tags: ["epcot", "hollywood_studios", "dvc", "skyliner"],
    provenance: stable,
  },
  {
    id: "resort_copper_creek",
    entityType: "resort",
    name: "Copper Creek Villas & Cabins at Disney's Wilderness Lodge",
    aliases: ["copper creek", "ccv"],
    resortType: "dvc",
    areaId: "area_mk_resort_area",
    parkAccess: ["park_magic_kingdom"],
    transportationModes: ["boat", "bus"],
    tags: ["magic_kingdom", "dvc", "boat"],
    provenance: stable,
  },
  {
    id: "resort_boulder_ridge",
    entityType: "resort",
    name: "Boulder Ridge Villas at Disney's Wilderness Lodge",
    aliases: ["boulder ridge", "brv"],
    resortType: "dvc",
    areaId: "area_mk_resort_area",
    parkAccess: ["park_magic_kingdom"],
    transportationModes: ["boat", "bus"],
    tags: ["magic_kingdom", "dvc", "boat"],
    provenance: stable,
  },
];

function dining(
  id: string,
  name: string,
  locationId: string,
  serviceType: HannaDiningLocation["serviceType"],
  cuisine: string,
  mealPeriods: HannaDiningLocation["mealPeriods"],
  costTier: HannaDiningLocation["costTier"],
  toddlerFit: HannaDiningLocation["toddlerFit"],
  reservationPlanning: HannaDiningLocation["reservationPlanning"],
  tags: string[],
  aliases: string[] = [],
  characterDining: HannaDiningLocation["characterDining"] = "no",
): HannaDiningLocation {
  return {
    id,
    entityType: "dining_location",
    name,
    aliases,
    locationId,
    serviceType,
    cuisine,
    mealPeriods,
    costTier,
    costTierProvenance: diningReview,
    characterDining,
    toddlerFit,
    reservationPlanning,
    tags,
    provenance: stable,
  };
}

const HANNA_V1_DINING_BASE: HannaDiningLocation[] = [
  { id: "dining_via_napoli", entityType: "dining_location", name: "Via Napoli Ristorante e Pizzeria", aliases: ["via napoli"], locationId: "area_epcot_italy", serviceType: "table_service", cuisine: "Italian; pizza and pasta", mealPeriods: ["lunch", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "strong", reservationPlanning: "usually_recommended", tags: ["epcot", "world_showcase", "pizza", "lively", "toddler"], provenance: stable },
  { id: "dining_garden_grill", entityType: "dining_location", name: "Garden Grill Restaurant", aliases: ["garden grill"], locationId: "area_epcot_the_land", serviceType: "character_dining", cuisine: "American family-style", mealPeriods: ["breakfast", "lunch", "dinner"], costTier: "expensive", costTierProvenance: refreshable, toddlerFit: "strong", reservationPlanning: "usually_recommended", tags: ["epcot", "character_dining", "toddler", "family_style"], provenance: stable },
  { id: "dining_biergarten", entityType: "dining_location", name: "Biergarten Restaurant", aliases: ["biergarten"], locationId: "area_epcot_germany", serviceType: "table_service", cuisine: "German buffet-style", mealPeriods: ["lunch", "dinner"], costTier: "expensive", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "usually_recommended", tags: ["epcot", "world_showcase", "lively", "music", "buffet"], provenance: stable },
  { id: "dining_chefs_de_france", entityType: "dining_location", name: "Chefs de France", aliases: ["chefs de france"], locationId: "area_epcot_france", serviceType: "table_service", cuisine: "French bistro", mealPeriods: ["lunch", "dinner"], costTier: "expensive", costTierProvenance: refreshable, toddlerFit: "mixed", reservationPlanning: "usually_recommended", tags: ["epcot", "world_showcase", "france"], provenance: stable },
  { id: "dining_rose_and_crown", entityType: "dining_location", name: "Rose & Crown Dining Room", aliases: ["rose and crown", "rose & crown"], locationId: "area_epcot_uk", serviceType: "table_service", cuisine: "British pub fare", mealPeriods: ["lunch", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "helpful", tags: ["epcot", "world_showcase", "uk", "lively"], provenance: stable },
  { id: "dining_regal_eagle", entityType: "dining_location", name: "Regal Eagle Smokehouse", aliases: ["regal eagle"], locationId: "area_epcot_world_showcase", serviceType: "quick_service", cuisine: "American barbecue", mealPeriods: ["lunch", "dinner"], costTier: "value", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "usually_not_needed", tags: ["epcot", "quick_service", "flexible"], provenance: stable },
  { id: "dining_space_220", entityType: "dining_location", name: "Space 220 Restaurant", aliases: ["space 220"], locationId: "park_epcot", serviceType: "table_service", cuisine: "American prix-fixe style", mealPeriods: ["lunch", "dinner"], costTier: "premium", costTierProvenance: refreshable, toddlerFit: "mixed", reservationPlanning: "usually_recommended", tags: ["epcot", "themed", "hard_to_book"], provenance: stable },
  { id: "dining_trattoria_al_forno", entityType: "dining_location", name: "Trattoria al Forno", aliases: ["trattoria"], locationId: "resort_boardwalk_villas", serviceType: "table_service", cuisine: "Italian-American", mealPeriods: ["breakfast", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "helpful", tags: ["boardwalk", "epcot_resort_area", "easy_return"], provenance: stable },
  { id: "dining_ale_and_compass", entityType: "dining_location", name: "Ale & Compass Restaurant", aliases: ["ale and compass"], locationId: "area_epcot_resort_area", serviceType: "table_service", cuisine: "New England-inspired American", mealPeriods: ["breakfast", "lunch", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "helpful", tags: ["epcot_resort_area", "calmer"], provenance: stable },
  { id: "dining_beaches_and_cream", entityType: "dining_location", name: "Beaches & Cream Soda Shop", aliases: ["beaches and cream"], locationId: "area_epcot_resort_area", serviceType: "table_service", cuisine: "Burgers, sandwiches, and ice cream", mealPeriods: ["lunch", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "strong", reservationPlanning: "usually_recommended", tags: ["epcot_resort_area", "ice_cream", "toddler"], provenance: stable },
  { id: "dining_crystal_palace", entityType: "dining_location", name: "The Crystal Palace", aliases: ["crystal palace"], locationId: "park_magic_kingdom", serviceType: "character_dining", cuisine: "American buffet-style", mealPeriods: ["breakfast", "lunch", "dinner"], costTier: "expensive", costTierProvenance: refreshable, toddlerFit: "strong", reservationPlanning: "usually_recommended", tags: ["magic_kingdom", "character_dining", "toddler"], provenance: stable },
  { id: "dining_liberty_tree_tavern", entityType: "dining_location", name: "Liberty Tree Tavern", aliases: ["liberty tree"], locationId: "park_magic_kingdom", serviceType: "table_service", cuisine: "American family-style", mealPeriods: ["lunch", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "usually_recommended", tags: ["magic_kingdom", "family_style"], provenance: stable },
  { id: "dining_ohana", entityType: "dining_location", name: "'Ohana", aliases: ["ohana"], locationId: "resort_polynesian_villas", serviceType: "table_service", cuisine: "Polynesian-inspired family-style", mealPeriods: ["breakfast", "dinner"], costTier: "expensive", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "usually_recommended", tags: ["magic_kingdom_resort_area", "monorail", "family_style"], provenance: stable },
  { id: "dining_chef_mickeys", entityType: "dining_location", name: "Chef Mickey's", aliases: ["chef mickeys", "chef mickey's"], locationId: "resort_bay_lake_tower", serviceType: "character_dining", cuisine: "American buffet-style", mealPeriods: ["breakfast", "dinner"], costTier: "expensive", costTierProvenance: refreshable, toddlerFit: "strong", reservationPlanning: "usually_recommended", tags: ["magic_kingdom_resort_area", "character_dining", "toddler"], provenance: stable },
  { id: "dining_grand_floridian_cafe", entityType: "dining_location", name: "Grand Floridian Cafe", aliases: ["grand floridian cafe"], locationId: "resort_grand_floridian_villas", serviceType: "table_service", cuisine: "American", mealPeriods: ["breakfast", "lunch", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "helpful", tags: ["magic_kingdom_resort_area", "monorail", "calmer"], provenance: stable },
  { id: "dining_topolinos", entityType: "dining_location", name: "Topolino's Terrace", aliases: ["topolinos", "topolino's"], locationId: "resort_riviera", serviceType: "table_service", cuisine: "French and Italian-inspired", mealPeriods: ["breakfast", "dinner"], costTier: "premium", costTierProvenance: refreshable, toddlerFit: "mixed", reservationPlanning: "usually_recommended", tags: ["riviera", "skyliner", "signature", "character_breakfast"], provenance: stable },
  { id: "dining_whispering_canyon", entityType: "dining_location", name: "Whispering Canyon Cafe", aliases: ["whispering canyon"], locationId: "resort_copper_creek", serviceType: "table_service", cuisine: "American barbecue-style skillets", mealPeriods: ["breakfast", "lunch", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "helpful", tags: ["wilderness_lodge", "lively", "family_style"], provenance: stable },
  { id: "dining_sanaa", entityType: "dining_location", name: "Sanaa", aliases: ["sanaa"], locationId: "resort_animal_kingdom_villas", serviceType: "table_service", cuisine: "African and Indian-inspired", mealPeriods: ["lunch", "dinner"], costTier: "moderate", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "helpful", tags: ["animal_kingdom_area", "bread_service"], provenance: stable },
  { id: "dining_hollywood_and_vine", entityType: "dining_location", name: "Hollywood & Vine", aliases: ["hollywood and vine"], locationId: "park_hollywood_studios", serviceType: "character_dining", cuisine: "American buffet-style", mealPeriods: ["breakfast", "lunch", "dinner"], costTier: "expensive", costTierProvenance: refreshable, toddlerFit: "strong", reservationPlanning: "usually_recommended", tags: ["hollywood_studios", "character_dining", "toddler"], provenance: stable },
  { id: "dining_woodys_lunch_box", entityType: "dining_location", name: "Woody's Lunch Box", aliases: ["woodys lunch box", "woody's"], locationId: "park_hollywood_studios", serviceType: "quick_service", cuisine: "American sandwiches and snacks", mealPeriods: ["breakfast", "lunch", "dinner"], costTier: "value", costTierProvenance: refreshable, toddlerFit: "good", reservationPlanning: "usually_not_needed", tags: ["hollywood_studios", "quick_service", "toy_story"], provenance: stable },
];

const HANNA_V1_DINING_EXPANSION: HannaDiningLocation[] = [
  dining("dining_cinderella_royal_table", "Cinderella's Royal Table", "park_magic_kingdom", "character_dining", "American prix-fixe castle dining", ["breakfast", "lunch", "dinner"], "premium", "mixed", "usually_recommended", ["magic_kingdom", "character_dining", "castle", "special_occasion", "reservation_strongly_recommended"], ["cinderellas royal table", "crt"], "yes"),
  dining("dining_be_our_guest", "Be Our Guest Restaurant", "area_mk_fantasyland", "table_service", "French-inspired prix-fixe", ["lunch", "dinner"], "premium", "mixed", "usually_recommended", ["magic_kingdom", "fantasyland", "themed", "special_occasion", "reservation_strongly_recommended"], ["be our guest", "bog"]),
  dining("dining_skippers_canteen", "Jungle Navigation Co. LTD Skipper Canteen", "area_mk_adventureland", "table_service", "Asian, African, and Latin-inspired", ["lunch", "dinner"], "moderate", "good", "helpful", ["magic_kingdom", "adventureland", "interesting_food", "casual", "table_service"], ["skipper canteen", "skippers canteen"]),
  dining("dining_columbia_harbour_house", "Columbia Harbour House", "area_mk_liberty_square", "quick_service", "Seafood and American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["magic_kingdom", "quick_service", "seafood", "indoor", "budget", "simple_foods"], ["columbia harbour house"]),
  dining("dining_pecos_bill", "Pecos Bill Tall Tale Inn and Cafe", "area_mk_frontierland", "quick_service", "Mexican-inspired American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["magic_kingdom", "quick_service", "mexican", "budget", "frontierland"], ["pecos bill"]),
  dining("dining_cosmic_rays", "Cosmic Ray's Starlight Cafe", "area_mk_tomorrowland", "quick_service", "American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["magic_kingdom", "quick_service", "budget", "simple_foods", "tomorrowland"], ["cosmic rays"]),
  dining("dining_pinocchio_village_haus", "Pinocchio Village Haus", "area_mk_fantasyland", "quick_service", "Italian-American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["magic_kingdom", "quick_service", "fantasyland", "pizza", "simple_foods"], ["pinocchio village haus"]),
  dining("dining_caseys_corner", "Casey's Corner", "area_mk_main_street", "quick_service", "American hot dogs and snacks", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["magic_kingdom", "main_street", "quick_service", "budget", "simple_foods", "near_exit"], ["caseys corner", "casey's"]),
  dining("dining_sleepy_hollow", "Sleepy Hollow", "area_mk_liberty_square", "snack_specialty", "Waffles and specialty snacks", ["breakfast", "lunch", "dinner", "snack"], "value", "good", "usually_not_needed", ["magic_kingdom", "snack_specialty", "budget", "casual"], ["sleepy hollow"]),
  dining("dining_plaza_restaurant", "The Plaza Restaurant", "area_mk_main_street", "table_service", "American sandwiches, salads, and ice cream", ["lunch", "dinner"], "moderate", "good", "helpful", ["magic_kingdom", "main_street", "casual", "simple_foods"], ["plaza restaurant"]),
  dining("dining_le_cellier", "Le Cellier Steakhouse", "area_epcot_canada", "signature", "Canadian steakhouse", ["lunch", "dinner"], "premium", "weak", "usually_recommended", ["epcot", "world_showcase", "steak", "signature", "special_occasion", "canada"], ["le cellier"]),
  dining("dining_teppan_edo", "Teppan Edo", "area_epcot_world_showcase", "table_service", "Japanese teppanyaki", ["lunch", "dinner"], "expensive", "good", "usually_recommended", ["epcot", "world_showcase", "japanese", "show_kitchen", "lively"], ["teppan edo"]),
  dining("dining_shiki_sai", "Shiki-Sai: Sushi Izakaya", "area_epcot_world_showcase", "table_service", "Japanese sushi and izakaya-style dining", ["lunch", "dinner"], "expensive", "mixed", "usually_recommended", ["epcot", "world_showcase", "japanese", "sushi", "nice_dinner"], ["shiki sai", "shiki-sai"]),
  dining("dining_la_hacienda", "La Hacienda de San Angel", "area_epcot_world_showcase", "table_service", "Mexican", ["dinner"], "expensive", "good", "usually_recommended", ["epcot", "world_showcase", "mexican", "waterfront", "nice_dinner"], ["la hacienda"]),
  dining("dining_san_angel_inn", "San Angel Inn Restaurante", "area_epcot_world_showcase", "table_service", "Mexican", ["lunch", "dinner"], "expensive", "mixed", "usually_recommended", ["epcot", "world_showcase", "mexican", "themed"], ["san angel inn"]),
  dining("dining_akershus", "Akershus Royal Banquet Hall", "area_epcot_world_showcase", "character_dining", "Norwegian-inspired character dining", ["breakfast", "lunch", "dinner"], "expensive", "strong", "usually_recommended", ["epcot", "world_showcase", "character_dining", "princesses", "toddler"], ["akershus"], "yes"),
  dining("dining_space_220_lounge", "Space 220 Lounge", "park_epcot", "lounge", "American lounge plates", ["lunch", "dinner"], "expensive", "mixed", "usually_recommended", ["epcot", "themed", "lounge", "space_220"], ["space 220 lounge"]),
  dining("dining_connections_eatery", "Connections Eatery", "area_epcot_world_celebration", "quick_service", "Global-inspired American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["epcot", "quick_service", "budget", "simple_foods", "indoor"], ["connections eatery"]),
  dining("dining_les_halles", "Les Halles Boulangerie-Patisserie", "area_epcot_france", "quick_service", "French bakery and cafe", ["breakfast", "lunch", "dinner", "snack"], "value", "good", "usually_not_needed", ["epcot", "world_showcase", "france", "bakery", "budget", "snack"], ["les halles"]),
  dining("dining_katsura_grill", "Katsura Grill", "area_epcot_world_showcase", "quick_service", "Japanese quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["epcot", "world_showcase", "japanese", "quick_service", "budget"], ["katsura grill"]),
  dining("dining_sunshine_seasons", "Sunshine Seasons", "area_epcot_the_land", "quick_service", "American and global quick service", ["breakfast", "lunch", "dinner"], "value", "good", "usually_not_needed", ["epcot", "the_land", "quick_service", "budget", "indoor", "simple_foods"], ["sunshine seasons"]),
  dining("dining_coral_reef", "Coral Reef Restaurant", "area_epcot_world_nature", "table_service", "Seafood and American", ["lunch", "dinner"], "expensive", "mixed", "usually_recommended", ["epcot", "seafood", "themed", "table_service"], ["coral reef"]),
  dining("dining_monsieur_paul", "Monsieur Paul", "area_epcot_france", "signature", "French fine dining", ["dinner"], "premium", "weak", "usually_recommended", ["epcot", "world_showcase", "france", "signature", "romantic", "special_occasion"], ["monsieur paul"]),
  dining("dining_spice_road_table", "Spice Road Table", "area_epcot_world_showcase", "table_service", "Mediterranean small plates", ["lunch", "dinner"], "moderate", "mixed", "helpful", ["epcot", "world_showcase", "mediterranean", "waterfront", "flexible"], ["spice road table"]),
  dining("dining_yorkshire_fish_shop", "Yorkshire County Fish Shop", "area_epcot_uk", "quick_service", "British fish and chips", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["epcot", "world_showcase", "uk", "quick_service", "budget"], ["yorkshire fish shop", "fish and chips"]),
  dining("dining_sci_fi_dine_in", "Sci-Fi Dine-In Theater Restaurant", "park_hollywood_studios", "table_service", "American drive-in theater-style dining", ["lunch", "dinner"], "moderate", "good", "usually_recommended", ["hollywood_studios", "themed", "simple_foods", "lively"], ["sci fi", "sci-fi"]),
  dining("dining_50s_prime_time", "50's Prime Time Cafe", "park_hollywood_studios", "table_service", "American comfort food", ["lunch", "dinner"], "moderate", "good", "usually_recommended", ["hollywood_studios", "themed", "lively", "simple_foods"], ["50s prime time", "prime time cafe"]),
  dining("dining_hollywood_brown_derby", "The Hollywood Brown Derby", "park_hollywood_studios", "signature", "American signature dining", ["lunch", "dinner"], "premium", "weak", "usually_recommended", ["hollywood_studios", "signature", "special_occasion", "nice_dinner"], ["brown derby", "hollywood brown derby"]),
  dining("dining_mama_melrose", "Mama Melrose's Ristorante Italiano", "park_hollywood_studios", "table_service", "Italian-American", ["lunch", "dinner"], "moderate", "good", "helpful", ["hollywood_studios", "italian", "pizza", "casual"], ["mama melrose", "mama melrose's"]),
  dining("dining_docking_bay_7", "Docking Bay 7 Food and Cargo", "area_hs_galaxys_edge", "quick_service", "Star Wars-themed American and global quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["hollywood_studios", "galaxys_edge", "quick_service", "themed"], ["docking bay 7"]),
  dining("dining_ronto_roasters", "Ronto Roasters", "area_hs_galaxys_edge", "quick_service", "Star Wars-themed wraps and breakfast", ["breakfast", "lunch", "dinner"], "value", "good", "usually_not_needed", ["hollywood_studios", "galaxys_edge", "quick_service", "budget"], ["ronto roasters"]),
  dining("dining_abc_commissary", "ABC Commissary", "park_hollywood_studios", "quick_service", "American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["hollywood_studios", "quick_service", "budget", "indoor", "simple_foods"], ["abc commissary"]),
  dining("dining_backlot_express", "Backlot Express", "park_hollywood_studios", "quick_service", "American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["hollywood_studios", "quick_service", "budget", "simple_foods"], ["backlot express"]),
  dining("dining_roundup_rodeo_bbq", "Roundup Rodeo BBQ", "area_hs_toy_story_land", "buffet_family_style", "Barbecue family-style", ["lunch", "dinner"], "expensive", "good", "usually_recommended", ["hollywood_studios", "toy_story", "barbecue", "family_style", "lively"], ["roundup rodeo", "roundup rodeo bbq"]),
  dining("dining_ogas_cantina", "Oga's Cantina", "area_hs_galaxys_edge", "lounge", "Star Wars-themed lounge", ["breakfast", "lunch", "dinner"], "moderate", "weak", "usually_recommended", ["hollywood_studios", "galaxys_edge", "lounge", "themed"], ["ogas cantina", "oga's"]),
  dining("dining_baseline_tap_house", "BaseLine Tap House", "park_hollywood_studios", "lounge", "California-inspired lounge snacks", ["lunch", "dinner", "snack"], "moderate", "weak", "usually_not_needed", ["hollywood_studios", "lounge", "adults", "snack"], ["baseline tap house"]),
  dining("dining_tusker_house", "Tusker House Restaurant", "area_ak_africa", "character_dining", "African-inspired buffet-style character dining", ["breakfast", "lunch", "dinner"], "expensive", "strong", "usually_recommended", ["animal_kingdom", "africa", "character_dining", "toddler", "buffet"], ["tusker house"], "yes"),
  dining("dining_tiffins", "Tiffins Restaurant", "area_ak_discovery_island", "signature", "African, Asian, and Latin-inspired signature dining", ["lunch", "dinner"], "premium", "weak", "usually_recommended", ["animal_kingdom", "signature", "special_occasion", "adults"], ["tiffins"]),
  dining("dining_yak_and_yeti", "Yak & Yeti Restaurant", "area_ak_asia", "table_service", "Asian-inspired", ["lunch", "dinner"], "moderate", "good", "usually_recommended", ["animal_kingdom", "asia", "asian", "table_service"], ["yak and yeti", "yak & yeti"]),
  dining("dining_flame_tree_bbq", "Flame Tree Barbecue", "area_ak_discovery_island", "quick_service", "American barbecue", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["animal_kingdom", "quick_service", "barbecue", "budget"], ["flame tree", "flame tree bbq"]),
  dining("dining_satuli_canteen", "Satu'li Canteen", "area_ak_pandora", "quick_service", "Pandora-themed bowls and American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["animal_kingdom", "pandora", "quick_service", "interesting_food", "budget"], ["satuli", "satu'li canteen"]),
  dining("dining_harambe_market", "Harambe Market", "area_ak_africa", "quick_service", "African-inspired quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["animal_kingdom", "africa", "quick_service", "budget"], ["harambe market"]),
  dining("dining_restaurantosaurus", "Restaurantosaurus", "area_ak_dinoland", "quick_service", "American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["animal_kingdom", "quick_service", "simple_foods", "budget"], ["restaurantosaurus"]),
  dining("dining_nomad_lounge", "Nomad Lounge", "area_ak_discovery_island", "lounge", "Global small plates and lounge", ["lunch", "dinner"], "moderate", "mixed", "helpful", ["animal_kingdom", "lounge", "scenic", "adults", "special_occasion"], ["nomad lounge"]),
  dining("dining_pizzafari", "Pizzafari", "area_ak_discovery_island", "quick_service", "Pizza and Italian-American quick service", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["animal_kingdom", "quick_service", "pizza", "simple_foods", "budget"], ["pizzafari"]),
  dining("dining_california_grill", "California Grill", "resort_bay_lake_tower", "signature", "Contemporary American signature dining", ["dinner"], "premium", "weak", "usually_recommended", ["magic_kingdom_resort_area", "monorail", "signature", "special_occasion", "scenic", "fireworks"], ["california grill"]),
  dining("dining_steakhouse_71", "Steakhouse 71", "resort_bay_lake_tower", "table_service", "American steakhouse", ["breakfast", "lunch", "dinner"], "moderate", "good", "helpful", ["magic_kingdom_resort_area", "monorail", "steak", "simple_foods"], ["steakhouse 71"]),
  dining("dining_contemporary_cafe", "Contempo Cafe", "resort_bay_lake_tower", "quick_service", "American quick service", ["breakfast", "lunch", "dinner"], "value", "good", "usually_not_needed", ["magic_kingdom_resort_area", "monorail", "quick_service", "simple_foods"], ["contempo cafe"]),
  dining("dining_kona_cafe", "Kona Cafe", "resort_polynesian_villas", "table_service", "American and Asian-inspired", ["breakfast", "lunch", "dinner"], "moderate", "good", "helpful", ["magic_kingdom_resort_area", "monorail", "polynesian", "casual"], ["kona cafe"]),
  dining("dining_capt_cooks", "Capt. Cook's", "resort_polynesian_villas", "quick_service", "American and Polynesian-inspired quick service", ["breakfast", "lunch", "dinner"], "value", "good", "usually_not_needed", ["magic_kingdom_resort_area", "monorail", "quick_service", "budget"], ["capt cooks", "capt. cook's"]),
  dining("dining_artist_point", "Story Book Dining at Artist Point", "resort_copper_creek", "character_dining", "Character dining with American cuisine", ["dinner"], "expensive", "strong", "usually_recommended", ["wilderness_lodge", "character_dining", "special_occasion", "toddler"], ["artist point", "story book dining"], "yes"),
  dining("dining_geyser_point", "Geyser Point Bar & Grill", "resort_copper_creek", "quick_service", "American casual grill", ["lunch", "dinner"], "moderate", "good", "helpful", ["wilderness_lodge", "casual", "scenic", "quick_service"], ["geyser point"]),
  dining("dining_narcoossees", "Narcoossee's", "resort_grand_floridian_villas", "signature", "Seafood and steak signature dining", ["dinner"], "premium", "weak", "usually_recommended", ["magic_kingdom_resort_area", "monorail", "seafood", "signature", "romantic", "special_occasion"], ["narcoossees", "narcoossee's"]),
  dining("dining_citricos", "Cítricos", "resort_grand_floridian_villas", "signature", "Mediterranean-inspired signature dining", ["dinner"], "premium", "weak", "usually_recommended", ["magic_kingdom_resort_area", "monorail", "signature", "romantic", "special_occasion"], ["citricos", "cítricos"]),
  dining("dining_1900_park_fare", "1900 Park Fare", "resort_grand_floridian_villas", "character_dining", "American buffet-style character dining", ["breakfast", "dinner"], "expensive", "strong", "usually_recommended", ["magic_kingdom_resort_area", "monorail", "character_dining", "toddler"], ["1900 park fare"], "yes"),
  dining("dining_gasparilla", "Gasparilla Island Grill", "resort_grand_floridian_villas", "quick_service", "American quick service", ["breakfast", "lunch", "dinner"], "value", "good", "usually_not_needed", ["magic_kingdom_resort_area", "quick_service", "budget", "simple_foods"], ["gasparilla"]),
  dining("dining_flying_fish", "Flying Fish", "resort_boardwalk_villas", "signature", "Seafood signature dining", ["dinner"], "premium", "weak", "usually_recommended", ["boardwalk", "epcot_resort_area", "seafood", "signature", "special_occasion"], ["flying fish"]),
  dining("dining_yachtsman_steakhouse", "Yachtsman Steakhouse", "area_epcot_resort_area", "signature", "Steakhouse signature dining", ["dinner"], "premium", "weak", "usually_recommended", ["epcot_resort_area", "steak", "signature", "special_occasion"], ["yachtsman", "yachtsman steakhouse"]),
  dining("dining_cape_may_cafe", "Cape May Cafe", "area_epcot_resort_area", "buffet_family_style", "American buffet-style dining", ["breakfast", "dinner"], "expensive", "good", "usually_recommended", ["epcot_resort_area", "buffet", "family_style", "character_breakfast"], ["cape may cafe"]),
  dining("dining_boardwalk_deli", "BoardWalk Deli", "resort_boardwalk_villas", "quick_service", "Bakery, sandwiches, and deli", ["breakfast", "lunch", "dinner", "snack"], "value", "good", "usually_not_needed", ["boardwalk", "epcot_resort_area", "quick_service", "bakery", "budget"], ["boardwalk deli"]),
  dining("dining_sebastians_bistro", "Sebastian's Bistro", "area_epcot_resort_area", "buffet_family_style", "Caribbean family-style", ["dinner"], "moderate", "good", "usually_recommended", ["skyliner", "epcot_resort_area", "family_style", "moderate"], ["sebastians bistro", "sebastian's"]),
  dining("dining_primo_piatto", "Primo Piatto", "resort_riviera", "quick_service", "French and Italian-inspired quick service", ["breakfast", "lunch", "dinner"], "value", "good", "usually_not_needed", ["riviera", "skyliner", "quick_service", "budget"], ["primo piatto"]),
  dining("dining_boma", "Boma - Flavors of Africa", "resort_animal_kingdom_villas", "buffet_family_style", "African-inspired buffet-style dining", ["breakfast", "dinner"], "expensive", "good", "usually_recommended", ["animal_kingdom_area", "buffet", "african", "family_style"], ["boma"]),
  dining("dining_jiko", "Jiko - The Cooking Place", "resort_animal_kingdom_villas", "signature", "African-inspired signature dining", ["dinner"], "premium", "weak", "usually_recommended", ["animal_kingdom_area", "african", "signature", "romantic", "special_occasion"], ["jiko"]),
  dining("dining_the_mara", "The Mara", "resort_animal_kingdom_villas", "quick_service", "African-inspired and American quick service", ["breakfast", "lunch", "dinner"], "value", "good", "usually_not_needed", ["animal_kingdom_area", "quick_service", "budget"], ["the mara"]),
  dining("dining_three_bridges", "Three Bridges Bar and Grill", "resort_saratoga_springs", "table_service", "American and Spanish-inspired", ["dinner"], "moderate", "good", "helpful", ["saratoga", "resort_dining", "casual"], ["three bridges"]),
  dining("dining_toledo", "Toledo - Tapas, Steak & Seafood", "area_epcot_resort_area", "signature", "Spanish-inspired steak and seafood", ["dinner"], "premium", "weak", "usually_recommended", ["resort_dining", "signature", "special_occasion", "steak", "seafood"], ["toledo"]),
  dining("dining_olivias", "Olivia's Cafe", "resort_saratoga_springs", "table_service", "American comfort food", ["breakfast", "lunch", "dinner"], "moderate", "good", "helpful", ["resort_dining", "casual", "simple_foods"], ["olivias", "olivia's"]),
  dining("dining_boatwrights", "Boatwright's Dining Hall", "area_epcot_resort_area", "table_service", "Southern American", ["dinner"], "moderate", "good", "helpful", ["resort_dining", "casual", "moderate"], ["boatwrights", "boatwright's"]),
  dining("dining_wine_bar_george", "Wine Bar George", "area_disney_springs", "table_service", "Wine bar with Mediterranean-inspired plates", ["lunch", "dinner"], "expensive", "weak", "usually_recommended", ["disney_springs", "wine", "special_occasion", "adults"], ["wine bar george"]),
  dining("dining_homecomin", "Chef Art Smith's Homecomin'", "area_disney_springs", "table_service", "Southern American", ["brunch", "lunch", "dinner"], "moderate", "good", "usually_recommended", ["disney_springs", "comfort_food", "lively"], ["homecomin", "chef art smiths homecomin"]),
  dining("dining_boathouse", "The BOATHOUSE", "area_disney_springs", "table_service", "Seafood and steak", ["lunch", "dinner"], "expensive", "mixed", "usually_recommended", ["disney_springs", "seafood", "scenic", "special_occasion"], ["boathouse"]),
  dining("dining_morimoto_asia", "Morimoto Asia", "area_disney_springs", "table_service", "Pan-Asian", ["lunch", "dinner"], "expensive", "mixed", "usually_recommended", ["disney_springs", "asian", "nice_dinner"], ["morimoto asia"]),
  dining("dining_raglan_road", "Raglan Road Irish Pub and Restaurant", "area_disney_springs", "table_service", "Irish pub fare", ["brunch", "lunch", "dinner"], "moderate", "good", "usually_recommended", ["disney_springs", "pub", "lively", "music"], ["raglan road"]),
  dining("dining_jaleo", "Jaleo by Jose Andres", "area_disney_springs", "table_service", "Spanish tapas", ["lunch", "dinner"], "expensive", "mixed", "usually_recommended", ["disney_springs", "spanish", "special_occasion"], ["jaleo"]),
  dining("dining_d_luxe_burger", "D-Luxe Burger", "area_disney_springs", "quick_service", "Burgers and fries", ["lunch", "dinner"], "value", "good", "usually_not_needed", ["disney_springs", "quick_service", "burgers", "simple_foods", "budget"], ["d-luxe burger", "deluxe burger"]),
  dining("dining_polite_pig", "The Polite Pig", "area_disney_springs", "quick_service", "Barbecue", ["lunch", "dinner"], "moderate", "good", "usually_not_needed", ["disney_springs", "quick_service", "barbecue", "lively"], ["polite pig"]),
  dining("dining_gideons_bakehouse", "Gideon's Bakehouse", "area_disney_springs", "snack_specialty", "Bakery and desserts", ["snack"], "moderate", "good", "usually_not_needed", ["disney_springs", "snack_specialty", "bakery", "dessert"], ["gideons", "gideon's bakehouse"]),
  dining("dining_earl_of_sandwich", "Earl of Sandwich", "area_disney_springs", "quick_service", "Sandwiches", ["breakfast", "lunch", "dinner"], "value", "good", "usually_not_needed", ["disney_springs", "quick_service", "budget", "simple_foods"], ["earl of sandwich"]),
  dining("dining_trex", "T-REX Cafe", "area_disney_springs", "table_service", "American themed dining", ["lunch", "dinner"], "moderate", "mixed", "usually_recommended", ["disney_springs", "themed", "lively", "simple_foods"], ["t rex", "trex", "t-rex"]),
];

export const HANNA_V1_DINING: HannaDiningLocation[] = [...HANNA_V1_DINING_BASE, ...HANNA_V1_DINING_EXPANSION];

const noHeight = { kind: "none" as const };
const unknownHeight = { kind: "unknown" as const };
const minHeight = (inches: number) => ({ kind: "minimum" as const, inches, provenance: heightReview });

export const HANNA_V1_ATTRACTIONS: HannaAttraction[] = [
  { id: "attr_mk_seven_dwarfs", entityType: "attraction", name: "Seven Dwarfs Mine Train", aliases: ["seven dwarfs", "mine train", "7dmt"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["coaster", "family_thrill"], heightRequirement: minHeight(38), typicalAudience: "family", indoorOutdoor: "mixed", physicalIntensity: "moderate", toddlerSuitability: "weak", planningTags: ["priority", "height_limited"], provenance: stable },
  { id: "attr_mk_peter_pan", entityType: "attraction", name: "Peter Pan's Flight", aliases: ["peter pan", "peter pans flight"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["classic", "dark_ride"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "good", planningTags: ["priority", "toddler", "indoor"], provenance: stable },
  { id: "attr_mk_small_world", entityType: "attraction", name: "\"it's a small world\"", aliases: ["small world", "its a small world"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["boat", "classic", "seated"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["toddler", "rest", "indoor", "cool_down", "long_seated"], provenance: stable },
  { id: "attr_mk_haunted_mansion", entityType: "attraction", name: "Haunted Mansion", aliases: ["haunted mansion"], parkId: "park_magic_kingdom", areaId: "area_mk_liberty_square", attractionType: "ride", experienceTags: ["dark_ride", "spooky"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "mixed", planningTags: ["indoor", "may_frighten", "classic"], provenance: stable },
  { id: "attr_mk_pirates", entityType: "attraction", name: "Pirates of the Caribbean", aliases: ["pirates"], parkId: "park_magic_kingdom", areaId: "area_mk_adventureland", attractionType: "ride", experienceTags: ["boat", "dark_ride"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, waterExposure: "minor", toddlerSuitability: "mixed", planningTags: ["indoor", "classic", "may_frighten"], provenance: stable },
  { id: "attr_mk_jungle_cruise", entityType: "attraction", name: "Jungle Cruise", aliases: ["jungle cruise"], parkId: "park_magic_kingdom", areaId: "area_mk_adventureland", attractionType: "ride", experienceTags: ["boat", "outdoor"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "low", toddlerSuitability: "good", planningTags: ["family", "seated"], provenance: stable },
  { id: "attr_mk_winnie_pooh", entityType: "attraction", name: "The Many Adventures of Winnie the Pooh", aliases: ["winnie the pooh", "pooh ride"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["dark_ride"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "strong", planningTags: ["toddler", "indoor", "fantasyland"], provenance: stable },
  { id: "attr_mk_dumbo", entityType: "attraction", name: "Dumbo the Flying Elephant", aliases: ["dumbo"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["spinner"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "outdoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["toddler", "fantasyland"], provenance: stable },
  { id: "attr_mk_little_mermaid", entityType: "attraction", name: "Under the Sea - Journey of The Little Mermaid", aliases: ["little mermaid ride", "under the sea"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["dark_ride"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "strong", planningTags: ["toddler", "indoor", "cool_down"], provenance: stable },
  { id: "attr_mk_mad_tea_party", entityType: "attraction", name: "Mad Tea Party", aliases: ["teacups", "mad tea party"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["spinner"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "moderate", toddlerSuitability: "good", planningTags: ["nearby_fantasyland"], provenance: stable },
  { id: "attr_mk_buzz", entityType: "attraction", name: "Buzz Lightyear's Space Ranger Spin", aliases: ["buzz lightyear", "space ranger spin"], parkId: "park_magic_kingdom", areaId: "area_mk_tomorrowland", attractionType: "ride", experienceTags: ["interactive", "dark_ride"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "good", planningTags: ["indoor", "family"], provenance: stable },
  { id: "attr_mk_space_mountain", entityType: "attraction", name: "Space Mountain", aliases: ["space mountain"], parkId: "park_magic_kingdom", areaId: "area_mk_tomorrowland", attractionType: "ride", experienceTags: ["coaster", "dark"], heightRequirement: minHeight(44), typicalAudience: "thrill", indoorOutdoor: "indoor", physicalIntensity: "high", darkRide: true, toddlerSuitability: "weak", planningTags: ["thrill", "height_limited"], provenance: stable },
  { id: "attr_mk_tron", entityType: "attraction", name: "TRON Lightcycle / Run", aliases: ["tron", "tron lightcycle run"], parkId: "park_magic_kingdom", areaId: "area_mk_tomorrowland", attractionType: "ride", experienceTags: ["coaster", "thrill"], heightRequirement: minHeight(48), typicalAudience: "thrill", indoorOutdoor: "mixed", physicalIntensity: "high", toddlerSuitability: "weak", planningTags: ["thrill", "height_limited"], provenance: stable },
  { id: "attr_mk_peoplemover", entityType: "attraction", name: "Tomorrowland Transit Authority PeopleMover", aliases: ["peoplemover", "tta"], parkId: "park_magic_kingdom", areaId: "area_mk_tomorrowland", attractionType: "ride", experienceTags: ["seated", "overview"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "mixed", physicalIntensity: "low", toddlerSuitability: "good", planningTags: ["rest", "pacing", "low_energy"], provenance: stable },
  { id: "attr_mk_carousel_progress", entityType: "attraction", name: "Walt Disney's Carousel of Progress", aliases: ["carousel of progress"], parkId: "park_magic_kingdom", areaId: "area_mk_tomorrowland", attractionType: "ride", experienceTags: ["theater", "seated"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "mixed", planningTags: ["rest", "indoor", "cool_down", "long_seated"], provenance: stable },
  { id: "attr_mk_philharmagic", entityType: "attraction", name: "Mickey's PhilharMagic", aliases: ["philharmagic"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["3d_show", "seated"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "good", planningTags: ["rest", "indoor", "cool_down", "fantasyland"], provenance: stable },
  { id: "attr_mk_magic_carpets", entityType: "attraction", name: "The Magic Carpets of Aladdin", aliases: ["magic carpets", "aladdin carpets"], parkId: "park_magic_kingdom", areaId: "area_mk_adventureland", attractionType: "ride", experienceTags: ["spinner"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "outdoor", physicalIntensity: "low", toddlerSuitability: "good", planningTags: ["toddler", "adventureland"], provenance: stable },
  { id: "attr_mk_tiki_room", entityType: "attraction", name: "Walt Disney's Enchanted Tiki Room", aliases: ["tiki room"], parkId: "park_magic_kingdom", areaId: "area_mk_adventureland", attractionType: "ride", experienceTags: ["seated", "show"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "good", planningTags: ["rest", "indoor", "cool_down", "discovery"], provenance: stable },
  { id: "attr_mk_barnstormer", entityType: "attraction", name: "The Barnstormer", aliases: ["barnstormer"], parkId: "park_magic_kingdom", areaId: "area_mk_fantasyland", attractionType: "ride", experienceTags: ["coaster", "junior"], heightRequirement: minHeight(35), typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "moderate", toddlerSuitability: "mixed", planningTags: ["height_limited", "fantasyland"], provenance: stable },
  { id: "attr_epcot_spaceship_earth", entityType: "attraction", name: "Spaceship Earth", aliases: ["spaceship earth"], parkId: "park_epcot", areaId: "area_epcot_world_celebration", attractionType: "ride", experienceTags: ["dark_ride", "slow"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "good", planningTags: ["indoor", "rest", "cool_down"], provenance: stable },
  { id: "attr_epcot_remy", entityType: "attraction", name: "Remy's Ratatouille Adventure", aliases: ["remy", "remys ratatouille adventure", "ratatouille"], parkId: "park_epcot", areaId: "area_epcot_france", attractionType: "ride", experienceTags: ["trackless", "family"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "moderate", toddlerSuitability: "good", planningTags: ["priority", "indoor", "world_showcase"], provenance: stable },
  { id: "attr_epcot_frozen", entityType: "attraction", name: "Frozen Ever After", aliases: ["frozen", "frozen ever after"], parkId: "park_epcot", areaId: "area_epcot_world_showcase", attractionType: "ride", experienceTags: ["boat", "family"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", waterExposure: "minor", toddlerSuitability: "good", planningTags: ["priority", "indoor", "world_showcase"], provenance: stable },
  { id: "attr_epcot_guardians", entityType: "attraction", name: "Guardians of the Galaxy: Cosmic Rewind", aliases: ["guardians", "cosmic rewind"], parkId: "park_epcot", areaId: "area_epcot_world_discovery", attractionType: "ride", experienceTags: ["coaster", "thrill"], heightRequirement: minHeight(42), typicalAudience: "thrill", indoorOutdoor: "indoor", physicalIntensity: "high", toddlerSuitability: "weak", planningTags: ["thrill", "height_limited"], provenance: stable },
  { id: "attr_epcot_soarin", entityType: "attraction", name: "Soarin' Around the World", aliases: ["soarin", "soarin around the world"], parkId: "park_epcot", areaId: "area_epcot_the_land", attractionType: "ride", experienceTags: ["simulator", "flying"], heightRequirement: minHeight(40), typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "moderate", toddlerSuitability: "weak", planningTags: ["indoor", "height_limited"], provenance: stable },
  { id: "attr_epcot_living_land", entityType: "attraction", name: "Living with the Land", aliases: ["living with the land"], parkId: "park_epcot", areaId: "area_epcot_the_land", attractionType: "ride", experienceTags: ["boat", "slow"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["rest", "indoor", "cool_down", "low_energy"], provenance: stable },
  { id: "attr_epcot_nemo", entityType: "attraction", name: "The Seas with Nemo & Friends", aliases: ["nemo", "seas with nemo"], parkId: "park_epcot", areaId: "area_epcot_world_nature", attractionType: "ride", experienceTags: ["dark_ride", "aquarium"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "strong", planningTags: ["toddler", "indoor", "cool_down", "rest"], provenance: stable },
  { id: "attr_epcot_imagination", entityType: "attraction", name: "Journey Into Imagination With Figment", aliases: ["figment", "journey into imagination"], parkId: "park_epcot", areaId: "area_epcot_world_nature", attractionType: "ride", experienceTags: ["dark_ride"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "good", planningTags: ["indoor", "cool_down"], provenance: stable },
  { id: "attr_epcot_mission_space", entityType: "attraction", name: "Mission: SPACE", aliases: ["mission space"], parkId: "park_epcot", areaId: "area_epcot_world_discovery", attractionType: "ride", experienceTags: ["simulator", "intense"], heightRequirement: minHeight(40), typicalAudience: "older_kids_adults", indoorOutdoor: "indoor", physicalIntensity: "high", toddlerSuitability: "weak", planningTags: ["height_limited", "high_sensory"], provenance: stable },
  { id: "attr_epcot_gran_fiesta", entityType: "attraction", name: "Gran Fiesta Tour Starring The Three Caballeros", aliases: ["gran fiesta tour", "three caballeros"], parkId: "park_epcot", areaId: "area_epcot_world_showcase", attractionType: "ride", experienceTags: ["boat", "slow"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["toddler", "indoor", "cool_down", "world_showcase"], provenance: stable },
  { id: "attr_epcot_moana", entityType: "attraction", name: "Journey of Water, Inspired by Moana", aliases: ["journey of water", "moana water"], parkId: "park_epcot", areaId: "area_epcot_world_nature", attractionType: "walkthrough", experienceTags: ["water", "interactive"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "low", waterExposure: "minor", toddlerSuitability: "good", planningTags: ["discovery", "world_nature", "family"], provenance: stable },
  { id: "attr_epcot_test_track", entityType: "attraction", name: "Test Track", aliases: ["test track"], parkId: "park_epcot", areaId: "area_epcot_world_discovery", attractionType: "ride", experienceTags: ["vehicle", "thrill"], heightRequirement: unknownHeight, typicalAudience: "older_kids_adults", indoorOutdoor: "mixed", physicalIntensity: "high", toddlerSuitability: "weak", planningTags: ["height_unknown", "current_status_live"], provenance: refreshable, status: "needs_review" },
  { id: "attr_hs_slinky_dog", entityType: "attraction", name: "Slinky Dog Dash", aliases: ["slinky dog", "slinky dog dash"], parkId: "park_hollywood_studios", areaId: "area_hs_toy_story_land", attractionType: "ride", experienceTags: ["coaster", "family_thrill"], heightRequirement: minHeight(38), typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "moderate", toddlerSuitability: "weak", planningTags: ["priority", "height_limited"], provenance: stable },
  { id: "attr_hs_runaway_railway", entityType: "attraction", name: "Mickey & Minnie's Runaway Railway", aliases: ["runaway railway", "mickey and minnie"], parkId: "park_hollywood_studios", areaId: "area_hs_hollywood_boulevard", attractionType: "ride", experienceTags: ["trackless", "family"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "moderate", toddlerSuitability: "good", planningTags: ["indoor", "family", "priority"], provenance: stable },
  { id: "attr_hs_toy_story_mania", entityType: "attraction", name: "Toy Story Mania!", aliases: ["toy story mania", "tsm"], parkId: "park_hollywood_studios", areaId: "area_hs_toy_story_land", attractionType: "ride", experienceTags: ["interactive", "3d"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "good", planningTags: ["indoor", "family"], provenance: stable },
  { id: "attr_hs_rise", entityType: "attraction", name: "Star Wars: Rise of the Resistance", aliases: ["rise of the resistance", "rise"], parkId: "park_hollywood_studios", areaId: "area_hs_galaxys_edge", attractionType: "ride", experienceTags: ["trackless", "star_wars"], heightRequirement: minHeight(40), typicalAudience: "older_kids_adults", indoorOutdoor: "indoor", physicalIntensity: "moderate", toddlerSuitability: "weak", planningTags: ["priority", "height_limited", "high_sensory"], provenance: stable },
  { id: "attr_hs_smugglers_run", entityType: "attraction", name: "Millennium Falcon: Smugglers Run", aliases: ["smugglers run", "millennium falcon"], parkId: "park_hollywood_studios", areaId: "area_hs_galaxys_edge", attractionType: "ride", experienceTags: ["simulator", "interactive"], heightRequirement: minHeight(38), typicalAudience: "older_kids_adults", indoorOutdoor: "indoor", physicalIntensity: "moderate", toddlerSuitability: "weak", planningTags: ["height_limited", "star_wars"], provenance: stable },
  { id: "attr_hs_tower_terror", entityType: "attraction", name: "The Twilight Zone Tower of Terror", aliases: ["tower of terror"], parkId: "park_hollywood_studios", areaId: "area_hs_sunset_boulevard", attractionType: "ride", experienceTags: ["drop", "thrill"], heightRequirement: minHeight(40), typicalAudience: "thrill", indoorOutdoor: "indoor", physicalIntensity: "high", toddlerSuitability: "weak", planningTags: ["thrill", "height_limited"], provenance: stable },
  { id: "attr_hs_rock_n_roller", entityType: "attraction", name: "Rock 'n' Roller Coaster", aliases: ["rock n roller coaster", "rock 'n' roller coaster"], parkId: "park_hollywood_studios", areaId: "area_hs_sunset_boulevard", attractionType: "ride", experienceTags: ["coaster", "thrill"], heightRequirement: minHeight(48), typicalAudience: "thrill", indoorOutdoor: "indoor", physicalIntensity: "high", toddlerSuitability: "weak", planningTags: ["thrill", "height_limited", "current_status_live"], provenance: refreshable, status: "needs_review" },
  { id: "attr_hs_alien_saucers", entityType: "attraction", name: "Alien Swirling Saucers", aliases: ["alien swirling saucers"], parkId: "park_hollywood_studios", areaId: "area_hs_toy_story_land", attractionType: "ride", experienceTags: ["spinner"], heightRequirement: minHeight(32), typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "moderate", toddlerSuitability: "mixed", planningTags: ["height_limited", "toy_story"], provenance: stable },
  { id: "attr_hs_muppetvision", entityType: "attraction", name: "Muppet*Vision 3D", aliases: ["muppetvision", "muppet vision"], parkId: "park_hollywood_studios", areaId: "area_hs_hollywood_boulevard", attractionType: "ride", experienceTags: ["3d_show", "seated"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "good", planningTags: ["indoor", "rain", "rest"], provenance: stable },
  { id: "attr_hs_star_tours", entityType: "attraction", name: "Star Tours - The Adventures Continue", aliases: ["star tours"], parkId: "park_hollywood_studios", areaId: "area_hs_hollywood_boulevard", attractionType: "ride", experienceTags: ["simulator", "star_wars"], heightRequirement: minHeight(40), typicalAudience: "older_kids_adults", indoorOutdoor: "indoor", physicalIntensity: "moderate", toddlerSuitability: "weak", planningTags: ["indoor", "height_limited"], provenance: stable },
  { id: "attr_ak_safari", entityType: "attraction", name: "Kilimanjaro Safaris", aliases: ["safari", "kilimanjaro safaris"], parkId: "park_animal_kingdom", areaId: "area_ak_africa", attractionType: "animal_experience", experienceTags: ["animals", "vehicle"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["priority", "animal", "morning", "family"], provenance: stable },
  { id: "attr_ak_flight_of_passage", entityType: "attraction", name: "Avatar Flight of Passage", aliases: ["flight of passage", "fop"], parkId: "park_animal_kingdom", areaId: "area_ak_pandora", attractionType: "ride", experienceTags: ["simulator", "thrill"], heightRequirement: minHeight(44), typicalAudience: "thrill", indoorOutdoor: "indoor", physicalIntensity: "high", toddlerSuitability: "weak", planningTags: ["priority", "height_limited"], provenance: stable },
  { id: "attr_ak_navi", entityType: "attraction", name: "Na'vi River Journey", aliases: ["navi river journey", "na vi river journey"], parkId: "park_animal_kingdom", areaId: "area_ak_pandora", attractionType: "ride", experienceTags: ["boat", "dark_ride"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "low", darkRide: true, toddlerSuitability: "good", planningTags: ["indoor", "family"], provenance: stable },
  { id: "attr_ak_expedition_everest", entityType: "attraction", name: "Expedition Everest", aliases: ["everest", "expedition everest"], parkId: "park_animal_kingdom", areaId: "area_ak_asia", attractionType: "ride", experienceTags: ["coaster", "thrill"], heightRequirement: minHeight(44), typicalAudience: "thrill", indoorOutdoor: "outdoor", physicalIntensity: "high", toddlerSuitability: "weak", planningTags: ["thrill", "height_limited"], provenance: stable },
  { id: "attr_ak_dinosaur", entityType: "attraction", name: "DINOSAUR", aliases: ["dinosaur"], parkId: "park_animal_kingdom", areaId: "area_ak_dinoland", attractionType: "ride", experienceTags: ["dark_ride", "intense"], heightRequirement: minHeight(40), typicalAudience: "older_kids_adults", indoorOutdoor: "indoor", physicalIntensity: "high", darkRide: true, toddlerSuitability: "weak", planningTags: ["height_limited", "may_frighten", "current_status_live"], provenance: refreshable, status: "needs_review" },
  { id: "attr_ak_kali", entityType: "attraction", name: "Kali River Rapids", aliases: ["kali", "kali river rapids"], parkId: "park_animal_kingdom", areaId: "area_ak_asia", attractionType: "ride", experienceTags: ["raft", "water"], heightRequirement: minHeight(38), typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "moderate", waterExposure: "likely", toddlerSuitability: "weak", planningTags: ["water", "height_limited"], provenance: stable },
  { id: "attr_ak_tough_bug", entityType: "attraction", name: "It's Tough to Be a Bug!", aliases: ["tough to be a bug", "its tough to be a bug"], parkId: "park_animal_kingdom", areaId: "area_ak_discovery_island", attractionType: "ride", experienceTags: ["3d_show", "sensory"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "indoor", physicalIntensity: "moderate", toddlerSuitability: "mixed", planningTags: ["may_frighten", "current_status_live", "indoor"], provenance: refreshable, status: "needs_review" },
  { id: "attr_ak_gorilla_falls", entityType: "attraction", name: "Gorilla Falls Exploration Trail", aliases: ["gorilla falls"], parkId: "park_animal_kingdom", areaId: "area_ak_africa", attractionType: "walkthrough", experienceTags: ["animals", "walking"], heightRequirement: noHeight, typicalAudience: "family", indoorOutdoor: "outdoor", physicalIntensity: "low", toddlerSuitability: "good", planningTags: ["animal", "near_safari", "discovery"], provenance: stable },
  { id: "support_mk_baby_care", entityType: "attraction", name: "Magic Kingdom Baby Care Center", aliases: ["magic kingdom baby care", "baby care center"], parkId: "park_magic_kingdom", areaId: "area_mk_main_street", attractionType: "walkthrough", experienceTags: ["family_support"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["baby_care", "rest", "indoor", "nap_disruption"], provenance: stable },
  { id: "support_epcot_baby_care", entityType: "attraction", name: "EPCOT Baby Care Center", aliases: ["epcot baby care"], parkId: "park_epcot", areaId: "area_epcot_world_showcase", attractionType: "walkthrough", experienceTags: ["family_support"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["baby_care", "rest", "indoor"], provenance: stable },
  { id: "support_hs_baby_care", entityType: "attraction", name: "Hollywood Studios Baby Care Center", aliases: ["hollywood studios baby care"], parkId: "park_hollywood_studios", areaId: "area_hs_hollywood_boulevard", attractionType: "walkthrough", experienceTags: ["family_support"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["baby_care", "rest", "indoor"], provenance: stable },
  { id: "support_ak_baby_care", entityType: "attraction", name: "Animal Kingdom Baby Care Center", aliases: ["animal kingdom baby care"], parkId: "park_animal_kingdom", areaId: "area_ak_discovery_island", attractionType: "walkthrough", experienceTags: ["family_support"], heightRequirement: noHeight, typicalAudience: "toddler", indoorOutdoor: "indoor", physicalIntensity: "low", toddlerSuitability: "strong", planningTags: ["baby_care", "rest", "indoor"], provenance: stable },
];

export const HANNA_V1_ENTERTAINMENT: HannaEntertainmentExperience[] = [
  { id: "ent_mk_fireworks", entityType: "entertainment", name: "Magic Kingdom nighttime fireworks", aliases: ["magic kingdom fireworks", "fireworks"], parkId: "park_magic_kingdom", areaId: "area_mk_main_street", entertainmentType: "nighttime_spectacular", experienceTags: ["nighttime"], indoorOutdoor: "outdoor", toddlerSuitability: "mixed", planningTags: ["live_showtime_required", "late_night", "high_sensory"], provenance: stable },
  { id: "ent_mk_parade", entityType: "entertainment", name: "Magic Kingdom daytime parade", aliases: ["magic kingdom parade", "parade"], parkId: "park_magic_kingdom", areaId: "area_mk_main_street", entertainmentType: "parade", experienceTags: ["characters"], indoorOutdoor: "outdoor", toddlerSuitability: "good", planningTags: ["live_showtime_required", "family"], provenance: stable },
  { id: "ent_epcot_luminous", entityType: "entertainment", name: "EPCOT nighttime spectacular", aliases: ["epcot fireworks", "luminous"], parkId: "park_epcot", areaId: "area_epcot_world_showcase", entertainmentType: "nighttime_spectacular", experienceTags: ["nighttime"], indoorOutdoor: "outdoor", toddlerSuitability: "mixed", planningTags: ["live_showtime_required", "late_night"], provenance: stable },
  { id: "ent_hs_frozen_singalong", entityType: "entertainment", name: "For the First Time in Forever: A Frozen Sing-Along Celebration", aliases: ["frozen sing along", "frozen sing-along"], parkId: "park_hollywood_studios", areaId: "area_hs_animation_courtyard", entertainmentType: "show", experienceTags: ["show", "characters"], indoorOutdoor: "indoor", toddlerSuitability: "good", planningTags: ["rain", "indoor", "rest", "family"], provenance: stable },
  { id: "ent_hs_beauty_beast", entityType: "entertainment", name: "Beauty and the Beast - Live on Stage", aliases: ["beauty and the beast show"], parkId: "park_hollywood_studios", areaId: "area_hs_sunset_boulevard", entertainmentType: "show", experienceTags: ["stage_show"], indoorOutdoor: "outdoor", toddlerSuitability: "good", planningTags: ["covered", "seated", "live_showtime_required"], provenance: stable },
  { id: "ent_hs_fantasmic", entityType: "entertainment", name: "Fantasmic!", aliases: ["fantasmic"], parkId: "park_hollywood_studios", areaId: "area_hs_sunset_boulevard", entertainmentType: "nighttime_spectacular", experienceTags: ["nighttime"], indoorOutdoor: "outdoor", toddlerSuitability: "mixed", planningTags: ["live_showtime_required", "late_night", "high_sensory"], provenance: stable },
  { id: "ent_ak_lion_king", entityType: "entertainment", name: "Festival of the Lion King", aliases: ["lion king show", "festival of the lion king"], parkId: "park_animal_kingdom", areaId: "area_ak_africa", entertainmentType: "show", experienceTags: ["stage_show", "music"], indoorOutdoor: "indoor", toddlerSuitability: "strong", planningTags: ["indoor", "rest", "family", "live_showtime_required"], provenance: stable },
  { id: "ent_ak_nemo", entityType: "entertainment", name: "Finding Nemo: The Big Blue... and Beyond!", aliases: ["finding nemo show", "nemo show"], parkId: "park_animal_kingdom", areaId: "area_ak_discovery_island", entertainmentType: "show", experienceTags: ["stage_show"], indoorOutdoor: "indoor", toddlerSuitability: "good", planningTags: ["indoor", "rest", "family", "live_showtime_required"], provenance: stable },
];

export const HANNA_V1_TRANSPORTATION: HannaTransportationConnection[] = [
  { id: "transport_boardwalk_epcot_gateway", entityType: "transportation_connection", name: "BoardWalk to EPCOT via International Gateway", fromId: "resort_boardwalk_villas", toId: "park_epcot", modes: ["walk", "boat"], complexity: "easy", strollerNotes: "Walking avoids folding a stroller for bus transportation.", tags: ["boardwalk", "epcot", "stroller", "nap"], provenance: stable },
  { id: "transport_blt_mk_walk", entityType: "transportation_connection", name: "Bay Lake Tower walking path to Magic Kingdom", fromId: "resort_bay_lake_tower", toId: "park_magic_kingdom", modes: ["walk"], complexity: "easy", strollerNotes: "The walking path can be useful when leaving with a tired child.", tags: ["magic_kingdom", "late_night", "stroller"], provenance: stable },
  { id: "transport_riviera_epcot_skyliner", entityType: "transportation_connection", name: "Riviera Resort to EPCOT by Disney Skyliner", fromId: "resort_riviera", toId: "park_epcot", modes: ["skyliner"], complexity: "moderate", tags: ["epcot", "skyliner"], provenance: stable },
];

export const HANNA_V1_PLANNING_SIGNALS: HannaPlanningSignal[] = [
  {
    id: "signal_boardwalk_epcot_gateway",
    entityType: "planning_signal",
    name: "BoardWalk EPCOT convenience",
    appliesToIds: ["resort_boardwalk_villas", "park_epcot", "area_epcot_international_gateway"],
    contexts: ["epcot_day", "toddler", "stroller", "nap", "transportation"],
    priority: "high",
    shortReason: "BoardWalk-area lodging is especially convenient for EPCOT days because International Gateway makes leaving for naps or an early night much easier.",
    tags: ["boardwalk", "epcot", "toddler", "nap"],
    provenance: editorial,
  },
  {
    id: "signal_lively_dining_toddler",
    entityType: "planning_signal",
    name: "Lively dining can help toddlers",
    appliesToIds: ["dining_via_napoli", "dining_biergarten", "dining_beaches_and_cream", "dining_whispering_canyon"],
    contexts: ["toddler", "dining", "family"],
    priority: "medium",
    shortReason: "A lively, casual room can be easier with a toddler than a quiet formal meal where normal kid noise feels more noticeable.",
    tags: ["toddler", "dining"],
    provenance: editorial,
  },
  {
    id: "signal_easy_return_nap",
    entityType: "planning_signal",
    name: "Easy resort return around nap time",
    appliesToIds: ["resort_boardwalk_villas", "park_epcot", "resort_bay_lake_tower", "park_magic_kingdom"],
    contexts: ["toddler", "nap", "short_stay", "transportation"],
    priority: "high",
    shortReason: "For short stays with toddlers, easy resort return can matter more than squeezing in one more attraction or saving a small number of points.",
    tags: ["toddler", "nap", "transportation"],
    provenance: editorial,
  },
  {
    id: "signal_late_mk_walk",
    entityType: "planning_signal",
    name: "Walking access after late Magic Kingdom nights",
    appliesToIds: ["resort_bay_lake_tower", "resort_grand_floridian_villas", "park_magic_kingdom"],
    contexts: ["late_night", "magic_kingdom", "stroller", "toddler"],
    priority: "high",
    shortReason: "Walking access can be unusually valuable after a late Magic Kingdom night when a toddler is asleep in the stroller.",
    tags: ["magic_kingdom", "late_night", "stroller"],
    provenance: editorial,
  },
  {
    id: "signal_transport_friction_short_stay",
    entityType: "planning_signal",
    name: "Transportation friction on short stays",
    appliesToIds: ["park_epcot", "park_magic_kingdom"],
    contexts: ["short_stay", "transportation", "dvc_points", "toddler"],
    priority: "medium",
    shortReason: "On short trips, lowering transportation friction can be more valuable than a modest points saving.",
    tags: ["transportation", "dvc_points"],
    provenance: editorial,
  },
  {
    id: "signal_mk_toddler_fantasyland_cluster",
    entityType: "planning_signal",
    name: "Magic Kingdom toddler Fantasyland cluster",
    appliesToIds: ["park_magic_kingdom", "area_mk_fantasyland", "attr_mk_small_world", "attr_mk_winnie_pooh", "attr_mk_little_mermaid", "attr_mk_dumbo"],
    contexts: ["toddler", "magic_kingdom", "geography", "pacing"],
    priority: "high",
    shortReason: "With a toddler at Magic Kingdom, grouping Fantasyland experiences avoids wasting energy crossing the park for rides that are not meaningfully better for this age.",
    tags: ["magic_kingdom", "toddler", "geography"],
    provenance: editorial,
  },
  {
    id: "signal_heat_indoor_reset",
    entityType: "planning_signal",
    name: "Indoor reset during heat or rain",
    appliesToIds: ["attr_mk_small_world", "attr_mk_carousel_progress", "attr_epcot_living_land", "attr_epcot_nemo", "ent_hs_frozen_singalong", "ent_ak_lion_king"],
    contexts: ["weather", "rest", "family", "indoor", "cool_down"],
    priority: "high",
    shortReason: "When heat, rain, or fatigue changes the day, an indoor seated experience can protect the rest of the plan better than chasing another headline ride.",
    tags: ["weather", "rest", "family"],
    provenance: editorial,
  },
  {
    id: "signal_safari_morning_not_guarantee",
    entityType: "planning_signal",
    name: "Safari morning judgment",
    appliesToIds: ["attr_ak_safari", "park_animal_kingdom", "area_ak_africa"],
    contexts: ["animal_kingdom", "morning", "priority", "family"],
    priority: "medium",
    shortReason: "Kilimanjaro Safaris is often a sensible early Animal Kingdom priority, but Hanna should not promise animal activity or current waits without live data.",
    tags: ["animal_kingdom", "safari", "morning"],
    provenance: editorial,
  },
  {
    id: "signal_missed_nap_lower_energy",
    entityType: "planning_signal",
    name: "Missed nap lower-energy pivot",
    appliesToIds: ["park_magic_kingdom", "attr_mk_philharmagic", "attr_mk_small_world", "attr_mk_peoplemover", "support_mk_baby_care"],
    contexts: ["toddler", "nap", "rest", "low_energy", "pacing"],
    priority: "high",
    shortReason: "After a missed nap, the smarter move is often a short cluster of lower-energy nearby options or a true reset, not a maximal ride plan.",
    tags: ["toddler", "nap", "rest"],
    provenance: editorial,
  },
  {
    id: "signal_epcot_three_hours_toddler",
    entityType: "planning_signal",
    name: "Short EPCOT toddler priority",
    appliesToIds: ["park_epcot", "attr_epcot_nemo", "attr_epcot_living_land", "attr_epcot_gran_fiesta", "attr_epcot_remy"],
    contexts: ["epcot_day", "toddler", "short_stay", "pacing", "priority"],
    priority: "high",
    shortReason: "With limited EPCOT time and a toddler, prioritize a tight set of gentle experiences rather than bouncing between far-apart headliners.",
    tags: ["epcot", "toddler", "pacing"],
    provenance: editorial,
  },
  {
    id: "signal_world_showcase_discovery",
    entityType: "planning_signal",
    name: "World Showcase nearby discovery",
    appliesToIds: ["area_epcot_world_showcase", "attr_epcot_gran_fiesta", "area_epcot_france", "area_epcot_uk"],
    contexts: ["discovery", "world_showcase", "geography", "pacing"],
    priority: "medium",
    shortReason: "World Showcase is good for small nearby discoveries when there is only a little time before dinner; do not turn that into a cross-park mission.",
    tags: ["epcot", "discovery", "world_showcase"],
    provenance: editorial,
  },
  {
    id: "signal_midday_table_service_reset",
    entityType: "planning_signal",
    name: "Midday table-service reset",
    appliesToIds: ["park_epcot", "park_magic_kingdom", "park_hollywood_studios", "park_animal_kingdom"],
    contexts: ["dining", "weather", "rest", "family", "toddler", "lunch"],
    priority: "medium",
    shortReason: "A midday table-service meal can be valuable as an air-conditioned reset, especially when heat or toddler fatigue is shaping the day.",
    tags: ["dining", "rest", "toddler"],
    provenance: editorial,
  },
  {
    id: "signal_world_showcase_dinner_pairs_evening",
    entityType: "planning_signal",
    name: "World Showcase dinner pairs with EPCOT evening",
    appliesToIds: ["park_epcot", "area_epcot_world_showcase", "dining_via_napoli", "dining_biergarten", "dining_rose_and_crown", "dining_spice_road_table"],
    contexts: ["dining", "epcot_day", "world_showcase", "dinner", "geography"],
    priority: "high",
    shortReason: "World Showcase dinner pairs naturally with an EPCOT evening because it avoids an extra transportation leg and keeps the plan geographically coherent.",
    tags: ["epcot", "dining", "geography"],
    provenance: editorial,
  },
  {
    id: "signal_leaving_park_for_dining_friction",
    entityType: "planning_signal",
    name: "Leaving a park for dining friction",
    appliesToIds: ["park_magic_kingdom", "park_epcot", "park_hollywood_studios", "park_animal_kingdom", "area_mk_resort_area", "area_epcot_resort_area"],
    contexts: ["dining", "transportation", "pacing", "family"],
    priority: "medium",
    shortReason: "Leaving a park for resort dining can be worth it, but the park exit, transportation, meal, and return can consume more of the day than the restaurant name suggests.",
    tags: ["dining", "transportation", "pacing"],
    provenance: editorial,
  },
  {
    id: "signal_character_breakfast_rope_drop_tradeoff",
    entityType: "planning_signal",
    name: "Character breakfast touring tradeoff",
    appliesToIds: ["dining_garden_grill", "dining_chef_mickeys", "dining_akershus", "dining_tusker_house", "dining_topolinos", "dining_1900_park_fare"],
    contexts: ["dining", "breakfast", "character_dining", "toddler", "pacing"],
    priority: "medium",
    shortReason: "Character breakfast can replace separate character time, but it may also consume prime early touring time, so location and priorities matter.",
    tags: ["dining", "character_dining", "toddler"],
    provenance: editorial,
  },
  {
    id: "signal_toddler_dining_proximity_over_prestige",
    entityType: "planning_signal",
    name: "Toddler dining proximity over prestige",
    appliesToIds: ["park_epcot", "park_magic_kingdom", "resort_boardwalk_villas", "resort_bay_lake_tower", "dining_via_napoli", "dining_beaches_and_cream", "dining_steakhouse_71"],
    contexts: ["dining", "toddler", "transportation", "nap", "family"],
    priority: "high",
    shortReason: "With a tired toddler, proximity and an easy exit can matter more than picking the most celebrated restaurant.",
    tags: ["dining", "toddler", "transportation"],
    provenance: editorial,
  },
  {
    id: "signal_selective_eater_simple_foods",
    entityType: "planning_signal",
    name: "Selective eater simple-food context",
    appliesToIds: ["dining_via_napoli", "dining_beaches_and_cream", "dining_woodys_lunch_box", "dining_cosmic_rays", "dining_pizzafari", "dining_d_luxe_burger"],
    contexts: ["dining", "family", "toddler", "budget"],
    priority: "medium",
    shortReason: "For selective eaters, broad style and familiar-food fit can matter, but current menu-item guarantees still require current menu verification.",
    tags: ["dining", "selective_eater", "simple_foods"],
    provenance: editorial,
  },
];
